library(statsr)
library(dplyr)
library(ggplot2)

data(nycflights) # load flights dataset
names(nycflights) # view names of variables
?nycflights # view help for this dataset
str(nycflights) # view structure/description of data frame

# histogram showing departure delay times (minutes) on x-axis
x11()
ggplot(data = nycflights, aes(x = dep_delay)) + geom_histogram(binwidth = 150) 


# select flights with destination = RDU
rdu_flights <- nycflights %>% filter(dest == "RDU")
# filter function takes in a comparison and outputs the appropriate entries 

# plot delays in flights to RDU
x11()
ggplot(data = rdu_flights, aes(x = dep_delay)) + geom_histogram()

# A numerical summary for this data can be obtained
rdu_flights %>% summarise(mean_dd = mean(dep_delay), sd_dd = sd(dep_delay), num = n())
# mean_dd, sd_dd and num are user defined identifiers for the summary statistics generated by the functions

# multiple conditions for filteration can be specified using commas. | can be used for OR condition
sfo_feb_flights <- nycflights %>% filter(dest == "SFO", month == 2) # flights headed to SFO in February


dim(sfo_feb_flights)
"68 flights were headed to SFO in February"

# histogram to show arrival delays in sfo_feb_flights
x11()
ggplot(data = sfo_feb_flights, aes(x = arr_delay)) + geom_histogram()

# summary statistics for sfo_feb_flights
sfo_feb_flights %>% summarise(mean_ar = mean(arr_delay), sd_ar = sd(arr_delay), median_ar = median(arr_delay), max_ar = max(arr_delay), min_ar = min(arr_delay))

" -There is only one peak in the histogram, therefore it's unimodal
  -The histogram is right skewed, and mean is greater than median (-4.5 and -11 respectively)
  -Max delay was 196 minutes, which is more than 2 hours
  -Distribution is right skewed, so number of extreme values to the right is low.
  -Median is -11 minutes, so 50% flights arrive earlier than scheduled. From the histogram, it is clear that the majority of flights were not delayed."


# calculate summary statistics for various groups in data frame
rdu_flights %>% group_by(origin) %>% summarise(mean_dd = mean(dep_delay), sd_dd = sd(dep_delay), n = n())


# median and interquartile range for arr_delay of flights in the sfo_feb_flights data frame, grouped by carrier.
sfo_feb_flights %>% group_by(carrier) %>% summarise(median_delay = median(arr_delay), IQR(arr_delay))
"Delta and United Airlines have the highest IQR of arrival delays."

# average and median departure delays, grouped by month in descending order
nycflights %>%
  group_by(month) %>%
  summarise(mean_dd = mean(dep_delay), median_dd = median(dep_delay)) %>%
  arrange(desc(mean_dd))
"highest average and median departure delays were in July"

# visual comparison using side-by-side box plots
x11()
ggplot(nycflights, aes(x = factor(month), y = dep_delay)) + geom_boxplot()


# categorisation of flights
nycflights <- nycflights %>% mutate(dep_type = factor(ifelse(dep_delay < 5, "on time", "delayed")))


# percentage of on-time departures for each airport, shown under column ot_dep_rate
nycflights %>% 
  group_by(origin) %>% 
  summarise(ot_dep_rate = sum(dep_type == "on time") / n()) %>%
  arrange(desc(ot_dep_rate))
"LGA has the highest percentage of timely departures"

# visualisation of dep_type using segmented bar plot
x11()
ggplot(data = nycflights, aes(x = origin, fill = dep_type)) + geom_bar()

# average speed (mph) traveled by the plane for each flight
nycflights <- nycflights %>% mutate(avg_speed = distance * 60 /air_time)
nycflights %>% arrange(desc(avg_speed)) %>% select(tailnum, avg_speed)
"N666DN had the highest average speed."

# scatterplot of average speed vs distance
x11()
ggplot(data = nycflights, aes(x = distance, y = avg_speed)) + geom_point()
"There is an overall postive association between distance and average speed."


# check whether arrival was on time or not
nycflights <- nycflights %>% mutate(arr_type = factor(ifelse(arr_delay <= 0 , yes = "on time", no = "delayed")))

nycflights %>% group_by(arr_type) %>% summarise(late_dep_pc = sum(dep_type == "delayed")*100/n(), timely_dep_pc = sum(dep_type == "on time")*100/n())
"9.85% of flights that were delayed during departure arrived on time. *


* departure is considered delayed if it was late by 5 minutes or more.
"
